const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);
const e=require('../src/features/ai-mode/engine.ts'),g=require('../src/features/ai-mode/round.ts');
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name)}
const q=e.getQuestion('is_mammal'),pool=e.getInitialCandidates('easy');
const settings={difficulty:'medium',animalLevel:'easy',timer:0};
const make=()=>g.startRound(settings,null,1000,()=>0);
test('all animal pools come from bundled dataset',()=>{for(const level of ['easy','medium','hard'])assert(e.getInitialCandidates(level).every(a=>a.difficulty===level));assert.equal(e.getInitialCandidates('random').length,60)});
test('secrets are distinct across random boundaries',()=>{for(let i=0;i<100;i++){const ids=e.selectSecrets(pool,()=>i/100);assert.notEqual(...ids)}});
test('human view hides own secret and shows opponent',()=>{const s=make();assert.equal(g.visibleRound(s).own,null);assert.equal(g.visibleRound(s).opponent.id,s.aiSecret)});
test('initial AI candidates include every allowed animal',()=>assert.deepEqual(make().candidates,pool.map(a=>a.id)));
test('YES filters matching candidates',()=>assert(e.filterCandidates(pool,q,'yes').every(q.test)));
test('NO filters opposite candidates',()=>assert(e.filterCandidates(pool,q,'no').every(a=>!q.test(a))));
test('invalid answers preserve candidates',()=>assert.deepEqual(e.filterCandidates(pool,q,'invalid'),pool));
test('AI never repeats an asked question',()=>assert(!e.getPossibleQuestions(pool,[q.id]).some(x=>x.id===q.id)));
test('AI avoids non-splitting questions',()=>assert(e.getPossibleQuestions(pool,[]).every(x=>e.evaluateQuestionSplit(pool,x).score>0)));
test('hard AI maximizes balanced split',()=>{const best=e.chooseBestQuestion(pool,[]),act=e.chooseAiAction({candidates:pool,asked:[],difficulty:'hard'},()=>0);assert.equal(act.questionId,best.id)});
test('one candidate is guessed on every difficulty',()=>{for(const difficulty of ['easy','medium','hard'])assert.deepEqual(e.chooseAiAction({candidates:[pool[0]],asked:[],difficulty},()=>0),{type:'guess',animalId:pool[0].id})});
test('hard guesses at two while medium asks if possible',()=>{const c=[e.getAnimal(1),e.getAnimal(3)];assert.equal(e.chooseAiAction({candidates:c,asked:[],difficulty:'hard'},()=>0).type,'guess');assert.equal(e.chooseAiAction({candidates:c,asked:[],difficulty:'medium'},()=>.9).type,'question')});
test('reasoning receives no secret fields',()=>{const src=fs.readFileSync('src/features/ai-mode/engine.ts','utf8');const signature=src.split('export type ReasoningState =')[1].split('export type AiAction')[0];assert(!/secret|round/i.test(signature));const body=src.split('export function chooseAiAction')[1].split('export const validateGuess')[0];assert(!/secret/i.test(body))});
test('guess verifier correct/incorrect',()=>{assert(e.validateGuess(1,1));assert(!e.validateGuess(1,2))});
test('human structured answers use human animal',()=>{for(const animal of e.animals)for(const question of e.questions)assert.equal(e.answerHumanQuestion(question.id,animal.id),question.test(animal)?'yes':'no')});
test('human question delays then switches turn',()=>{let s=g.transition(make(),{type:'ask',questionId:q.id,now:1100});assert.equal(s.phase,'answering');s=g.transition(s,{type:'answer-human',now:1900});assert.equal(s.phase,'thinking');assert.equal(s.history[0].answer,'yes')});
test('human correct guess wins and awards once',()=>{const s=make(),win=g.transition(s,{type:'human-guess',animalId:s.humanSecret,now:1100});assert.equal(win.winner,'human');assert.equal(g.transition(win,{type:'human-guess',animalId:s.humanSecret,now:1100}).scores.human,1)});
test('human wrong guess passes turn',()=>assert.equal(g.transition(make(),{type:'human-guess',animalId:2,now:1200}).phase,'thinking'));
test('AI correct guess wins',()=>{const s={...make(),phase:'thinking'};assert.equal(g.transition(s,{type:'ai-action',action:{type:'guess',animalId:s.aiSecret},now:1500}).winner,'ai')});
test('AI wrong guess removes candidate and gives human turn',()=>{const s=g.transition({...make(),phase:'thinking'},{type:'ai-action',action:{type:'guess',animalId:1},now:1500});assert.equal(s.phase,'human');assert(!s.candidates.includes(1))});
test('AI filters solely from human answer',()=>{let s=g.transition({...make(),phase:'thinking'},{type:'ai-action',action:{type:'question',questionId:q.id},now:1500});s=g.transition(s,{type:'answer-ai',answer:'no',now:1600});assert.deepEqual(s.candidates,e.filterCandidates(pool,q,'no').map(a=>a.id));assert.equal(s.phase,'human')});
test('rematch preserves scoreboard, resets history and settings independently',()=>{const s=make();const win=g.transition(s,{type:'human-guess',animalId:s.humanSecret,now:1200});const next=g.startRound({...settings,difficulty:'hard'},win,2000,()=>.5);assert.equal(next.scores.human,1);assert.equal(next.history.length,0);assert.equal(next.id,2);assert.equal(next.settings.difficulty,'hard')});
test('timer expires locally and rejects late wins',()=>{const s=g.startRound({...settings,timer:20},null,1000,()=>0);const end=g.transition(s,{type:'human-guess',animalId:s.humanSecret,now:21000});assert.equal(end.reason,'timeout');assert.equal(end.scores.human,0);assert.equal(end.ended,21000)});
test('no timer leaves round active',()=>assert.equal(g.transition(make(),{type:'tick',now:999999}).phase,'human'));
test('AI files contain no network/auth/multiplayer dependencies',()=>{for(const f of ['engine.ts','round.ts','AiPage.tsx'])assert(!/fetch\(|WebSocket|authApi|gameStore|services\/api/.test(fs.readFileSync('src/features/ai-mode/'+f,'utf8')),f)});
test('removed mode has no active files/routes/state',()=>{for(const f of ['src/pages/SoloPage.tsx','src/pages/SoloPage.css','../backend/app/api/solo.py','../backend/tests/test_solo.py','../docs/SOLO_DETECTIVE.md'])assert(!fs.existsSync(f),f);assert(!/solo|detective/i.test(fs.readFileSync('src/App.tsx','utf8')));assert(!/solo_stars|solo_round/.test(fs.readFileSync('../backend/app/models/models.py','utf8')))});
test('bundled dataset matches multiplayer source fields',()=>assert(e.animals.every(a=>typeof a.can_swim==='boolean'&&typeof a.habitat==='string')));
console.log(`${passed} AI engine/state checks passed`);
