const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,f);
const p=require('../src/features/ai-mode/persistence.ts'),g=require('../src/features/ai-mode/round.ts');
const settings={difficulty:'medium',animalLevel:'easy',timer:0};
const initial=g.startRound(settings,null,1000,()=>0);
const encode=(round)=>JSON.stringify({version:1,round,settings,draft:'واش كيسبح؟'});
const json=value=>JSON.parse(JSON.stringify(value));
const restore=(round,now=1100)=>p.decodeSave(encode(round),now).round;
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name)};
test('human turn, draft, secrets and score survive',()=>{assert.deepEqual(restore(initial),initial);assert.equal(p.decodeSave(encode(initial),1100).draft,'واش كيسبح؟')});
const answering=g.transition(initial,{type:'ask-text',text:'واش كيسبح؟',now:1001});
test('pending Arabic answer resumes exactly once',()=>{assert.deepEqual(restore(answering),answering);let s=g.transition(restore(answering),{type:'answer-human',now:1200});s=g.transition(s,{type:'answer-human',now:1201});assert.equal(s.history.length,1)});
const thinking=g.transition(answering,{type:'answer-human',now:1200});
test('thinking phase keeps history and knowledge',()=>assert.deepEqual(restore(thinking),json(thinking)));
const question=g.transition(thinking,{type:'ai-action',action:{type:'question',questionId:'is_mammal'},now:1300});
test('AI question restores same question',()=>assert.deepEqual(restore(question),json(question)));
test('finished round does not award score twice',()=>{const won=g.transition(initial,{type:'human-guess',animalId:initial.humanSecret,now:1400});assert.deepEqual(restore(won,30000),json(won));assert.equal(restore(won).scores.human,1)});
test('deadline is unchanged and expired round ends',()=>{const timed={...initial,settings:{...settings,timer:20}};assert.equal(restore(timed,5000).started,1000);const expired=restore(timed,22000);assert.equal(expired.phase,'finished');assert.equal(expired.reason,'timeout');assert.equal(expired.ended,21000);assert.deepEqual(expired.scores,{human:0,ai:0})});
test('invalid saves fail safely',()=>{for(const raw of [null,'{','null','{}',encode({...initial,humanSecret:999}),encode({...question,pending:undefined}),encode({...initial,history:[{kind:'guess',value:999}]}),JSON.stringify({version:2,round:initial,settings,draft:''})])assert.equal(p.decodeSave(raw,1100),null)});
test('blocked storage is recoverable',()=>{global.localStorage={getItem(){throw Error('blocked')},setItem(){throw Error('quota')}};assert.equal(p.loadAiSave(),null);assert.equal(p.saveAiRound(initial,settings,''),false)});
console.log(`${count} persistence checks passed`);
